version: '3'

services:
  api:
    build: .
    ports:
      - 3000:3000
    command: yarn docker:start
    volumes:
      - .:/usr/app
    networks:
      - net
    depends_on:
      - inmemory

  inmemory:
    image: redis:7-alpine
    command: redis-server --include /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - net
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

networks:
  net:
    driver: bridge
