version: '3'

services:
  api:
    build: .
    ports:
      - 3000:3000
    command: >
        yarn build && yarn start
    volumes:
      - ./dist:/usr/app/dist
    networks:
      - net
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - net

networks:
  net:
    driver: bridge
